# Home server
version: "3.5"
services:
    # Webserver
    nginx:
        image: lscr.io/linuxserver/nginx:latest
        container_name: root-nginx
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /path/to/appdata/config:/config
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
    samba:
        image: dperson/samba
        environment:
            - TZ=Etc/UTC
            - SHARE=Data;/mnt;yes;no;no;hong;none;none;Data
            - WORKGROUP=workgroup
            - USER=hong;120600
            - NMBD=True
        networks:
            - default
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        read_only: false
        tmpfs:
            - /tmp
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - /media/storage:/mnt/media/My Passport
    # # Managing all apps
    # homarr:
    #   container_name: test-homarr
    #   image: ghcr.io/ajnart/homarr:latest
    #   restart: unless-stopped
    #   volumes:
    #     - ./homarr/configs:/app/data/configs
    #     - ./homarr/icons:/app/public/icons
    #   ports:
    #     - 7575:7575
    # # Transcoding
    # tdarr:
    #   container_name: test-tdarr
    #   image: ghcr.io/haveagitgat/tdarr:latest
    #   restart: unless-stopped
    #   network_mode: bridge
    #   ports:
    #     - 8265:8265 # webUI port
    #     - 8266:8266 # server port
    #   environment:
    #     - TZ=Europe/London
    #     - PUID=1000
    #     - PGID=1000
    #     - UMASK_SET=002
    #     - serverIP=0.0.0.0
    #     - serverPort=8266
    #     - webUIPort=8265
    #     - internalNode=true
    #     - inContainer=true
    #     - nodeName=MyInternalNode
    #   volumes:
    #     - /docker/tdarr/server:/app/server
    #     - /docker/tdarr/configs:/app/configs
    #     - /docker/tdarr/logs:/app/logs
    #     - /media:/media/hong/
    #     - /transcode_cache:/temp
    # tdarr-node:
    #   container_name: test-tdarr-node
    #   image: ghcr.io/haveagitgat/tdarr_node:latest
    #   restart: unless-stopped
    #   network_mode: service:test-tdarr
    #   environment:
    #     - TZ=Europe/London
    #     - PUID=1000
    #     - PGID=1000
    #     - UMASK_SET=002
    #     - serverIP=0.0.0.0
    #     - serverPort=8266
    #     - inContainer=true
    #   volumes:
    #     - /docker/tdarr/configs:/app/configs
    #     - /docker/tdarr/logs:/app/logs
    #     - /media:/media/hong/
    #     - /transcode_cache:/temp
    # # Managing subtitles
    # bazarr:
    #   image: lscr.io/linuxserver/bazarr:latest
    #   container_name: test-bazarr
    #   environment:
    #       - PUID=1000
    #       - PGID=1000
    #       - TZ=Etc/UTC
    #   volumes:
    #     - /path/to/bazarr/config:/config
    #     - /path/to/movies:/media/hong/My Passport/Movies
    #   ports:
    #       - 6767:6767
    #   restart: unless-stopped
    # TODO: WIP from here, DO NOT PUSH
    # # Manage TV shows
    # sonarr:
    #   image: lscr.io/linuxserver/sonarr:latest
    #   container_name: test-sonarr
    #   environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Etc/UTC
    #   volumes:
    #     - /path/to/data:/config/sonarr
    #     - /path/to/tvseries:/media/hong/My Passport/TV_Shows
    #     - /path/to/downloadclient-downloads:/downloads #optional
    #   ports:
    #     - 8989:8989
    #   restart: unless-stopped
    # # Manage movies
    # radarr:
    #   image: lscr.io/linuxserver/radarr:latest
    #   container_name: test-radarr
    #   environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Etc/UTC
    #   volumes:
    #     - /path/to/data:/config/radarr
    #     - /path/to/movies:/media/hong/My Passport/Movies
    #     - /path/to/downloadclient-downloads:/downloads #optional
    #   ports:
    #     - 7878:7878
    #   restart: unless-stopped
    # # Torrent client
    # qbittorrent:
    #   image: lscr.io/linuxserver/qbittorrent:latest
    #   container_name: test-qbittorrent
    #   environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Etc/UTC
    #     - WEBUI_PORT=8080
    #   volumes:
    #     - /path/to/appdata/config:/config/qbittorrent
    #     - /path/to/downloads:/downloads
    #   ports:
    #     - 8080:8080
    #     - 6881:6881
    #     - 6881:6881/udp
    #   restart: unless-stopped
    # # Media server
    # # Plex media server
    # plex:
    #   image: lscr.io/linuxserver/plex:latest
    #   container_name: test-plex
    #   network_mode: host
    #   environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Etc/UTC
    #     - VERSION=docker
    #     # - PLEX_CLAIM= #optional
    #   volumes:
    #     - /path/to/library:/config/plex
    #     - /path/to/tvseries:/media/hong/My Passport/TV_Shows
    #     - /path/to/movies:/media/hong/My Passport/Movies
    #   restart: unless-stopped
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: root-jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            # - JELLYFIN_PublishedServerUrl=192.168.1.105 #optional
        volumes:
            - /path/to/library:/config/jellyfin
            - /path/to/tvseries:/media/hong/My Passport/TV_Shows
            - /path/to/movies:/media/hong/My Passport/Movies
        ports:
            - 8096:8096
            # - 8920:8920 #optional
            # - 7359:7359/udp #optional
            # - 1900:1900/udp #optional
        restart: unless-stopped
    # Help users other than admin request content
    ombi:
        image: lscr.io/linuxserver/ombi:latest
        container_name: root-ombi
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /path/to/appdata/config:/config
        ports:
            - 3579:3579
        restart: unless-stopped
