services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - WEBUI_PORT=8082
        volumes:
            - ./assets/torrents/qbit/config:/config
            - /downloads:/downloads
            - /media:/media
        ports:
            - 8082:8080
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./assets/torrents/bazarr/config:/config
            - /home/hong/Media/WesternDigital/Torrents/Movies:/movies
            - /home/hong/Media/WesternDigital/Torrents/TV_Shows:/tv
            - /home/hong/Media/SeagateExpansion/Torrents/Movies:/movies
            - /home/hong/Media/SeagateExpansion/Torrents/Shows:/tv
        ports:
            - 6767:6767
        restart: unless-stopped
