# Kube State Metrics ServiceAccount (identity for this process to interact with k8s API server)
apiVersion: v1
kind: ServiceAccount

metadata:
  name: agent-kube-state-metrics
automountServiceAccountToken: false
