version: "3.7"
services:
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    home_assistant:
        container_name: home_assistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        volumes:
            - ../../assets/general/home_assistant/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        privileged: true
        network_mode: host
