{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: infra
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.infra.svc.cluster.local:{{ .Values.prometheus.port }}
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:{{ .Values.loki.port }}
        editable: true
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: "fake"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          ports:
            - containerPort: {{ .Values.grafana.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.paths.config }}/infra/grafana/data
        - name: datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: infra
spec:
  selector:
    app: grafana
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      nodePort: {{ .Values.grafana.nodePort }}
  type: NodePort
{{- end }}
