{{- if .Values.ittools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: {{ .Values.ittools.image }}
          ports:
            - containerPort: {{ .Values.ittools.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: tools
spec:
  selector:
    app: it-tools
  ports:
    - port: {{ .Values.ittools.port }}
      targetPort: {{ .Values.ittools.port }}
      nodePort: {{ .Values.ittools.nodePort }}
  type: NodePort
{{- end }}
