# {{- if .Values.keel.enabled }}
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: keel
#   namespace: infra
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: keel
# rules:
#   - apiGroups: [""]
#     resources: ["namespaces"]
#     verbs: ["watch", "list"]
#   - apiGroups: [""]
#     resources: ["secrets"]
#     verbs: ["get", "watch", "list"]
#   - apiGroups: ["", "extensions", "apps"]
#     resources: ["*"]
#     verbs: ["get", "delete", "watch", "list", "update"]
#   - apiGroups: ["batch"]
#     resources: ["*"]
#     verbs: ["get", "delete", "watch", "list", "update", "create"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: keel
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: keel
# subjects:
#   - kind: ServiceAccount
#     name: keel
#     namespace: infra
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: keel
#   namespace: infra
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: keel
#   template:
#     metadata:
#       labels:
#         app: keel
#     spec:
#       serviceAccountName: keel
#       containers:
#         - name: keel
#           image: {{ .Values.keel.image }}
#           ports:
#             - containerPort: {{ .Values.keel.port }}
#           env:
#             - name: POLL
#               value: "1"
#             - name: KEEL_POLL_SCHEDULE
#               value: {{ .Values.keel.pollSchedule | quote }}
#             - name: BASIC_AUTH_USER
#               value: {{ .Values.keel.adminUser | quote }}
#             - name: BASIC_AUTH_PASSWORD
#               value: {{ .Values.keel.adminPassword | quote }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: keel
#   namespace: infra
# spec:
#   selector:
#     app: keel
#   ports:
#     - port: {{ .Values.keel.port }}
#       targetPort: {{ .Values.keel.port }}
#       nodePort: {{ .Values.keel.nodePort }}
#   type: NodePort
# {{- end }}
