{{- if .Values.plex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: {{ .Values.plex.hostNetwork }}
      containers:
        - name: plex
          image: {{ .Values.plex.image }}
          env:
            - name: PUID
              value: {{ .Values.linuxserver.puid | quote }}
            - name: PGID
              value: {{ .Values.linuxserver.pgid | quote }}
            - name: TZ
              value: {{ .Values.linuxserver.tz | quote }}
            - name: VERSION
              value: "docker"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tvshows
              mountPath: /tv
            - name: tvshows-wd
              mountPath: /tv-wd
            - name: movies
              mountPath: /movies
            - name: movies-wd
              mountPath: /movies-wd
            - name: music
              mountPath: /music
            - name: music-wd
              mountPath: /music-wd
            - name: dri
              mountPath: /dev/dri
          {{- if .Values.plex.privileged }}
          securityContext:
            privileged: true
          {{- end }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.paths.config }}/media/plex/config
        - name: tvshows
          hostPath:
            path: {{ .Values.paths.seagate }}/Shows
        - name: movies
          hostPath:
            path: {{ .Values.paths.seagate }}/Movies
        - name: music
          hostPath:
            path: {{ .Values.paths.seagate }}/Music
        - name: tvshows-wd
          hostPath:
            path: {{ .Values.paths.westernDigital }}/Shows
        - name: movies-wd
          hostPath:
            path: {{ .Values.paths.westernDigital }}/Movies
        - name: music-wd
          hostPath:
            path: {{ .Values.paths.westernDigital }}/Music
        - name: dri
          hostPath:
            path: /dev/dri
{{- end }}
