# {{- if .Values.radarr.enabled }}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: radarr
#   namespace: torrents
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: radarr
#   template:
#     metadata:
#       labels:
#         app: radarr
#     spec:
#       initContainers:
#         - name: fix-permissions
#           image: busybox
#           command: ["sh", "-c", "chown -R 1000:1000 /config"]
#           volumeMounts:
#             - name: config
#               mountPath: /config
#       containers:
#         - name: radarr
#           image: {{ .Values.radarr.image }}
#           ports:
#             - containerPort: {{ .Values.radarr.port }}
#           env:
#             - name: PUID
#               value: {{ .Values.linuxserver.puid | quote }}
#             - name: PGID
#               value: {{ .Values.linuxserver.pgid | quote }}
#             - name: TZ
#               value: {{ .Values.linuxserver.tz | quote }}
#           volumeMounts:
#             - name: config
#               mountPath: /config
#             - name: movies
#               mountPath: /movies
#             - name: movies-wd
#               mountPath: /movies-wd
#             - name: downloads
#               mountPath: /downloads
#       volumes:
#         - name: config
#           hostPath:
#             path: {{ .Values.paths.config }}/torrents/radarr/config
#         - name: movies
#           hostPath:
#             path: {{ .Values.paths.seagate }}/Movies
#         - name: movies-wd
#           hostPath:
#             path: {{ .Values.paths.westernDigital }}/Movies
#         - name: downloads
#           hostPath:
#             path: {{ .Values.radarr.volumes.downloads }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: radarr
#   namespace: torrents
# spec:
#   selector:
#     app: radarr
#   ports:
#     - port: {{ .Values.radarr.port }}
#       targetPort: {{ .Values.radarr.port }}
#       nodePort: {{ .Values.radarr.nodePort }}
#   type: NodePort
# {{- end }}
