{{- if .Values.stirlingpdf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: {{ .Values.stirlingpdf.image }}
          ports:
            - containerPort: {{ .Values.stirlingpdf.port }}
          volumeMounts:
            - name: config
              mountPath: /configs
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.paths.config }}/tools/stirling-pdf/configs
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: tools
spec:
  selector:
    app: stirling-pdf
  ports:
    - port: {{ .Values.stirlingpdf.port }}
      targetPort: {{ .Values.stirlingpdf.port }}
      nodePort: {{ .Values.stirlingpdf.nodePort }}
  type: NodePort
{{- end }}
