# Home server
version: "3.7"
services:
    # Dashboard for all apps
    homarr:
        container_name: homarr
        image: ghcr.io/ajnart/homarr:latest
        restart: unless-stopped
        volumes:
            - ../../assets/server_management/homarr/configs:/app/data/configs
            - ../../assets/server_management/homarr/data:/data
            - ../../assets/server_management/homarr/icons:/app/public/icons
        ports:
            - "7575:7575"
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    # Rustdesk remote server
    hbbs:
        container_name: hbbs
        # ports:
        #   - 21115:21115
        #   - 21116:21116
        #   - 21116:21116/udp
        #   - 21118:21118
        image: rustdesk/rustdesk-server:latest
        command: hbbs -r 127.0.0.1:21117
        volumes:
            - ./data:/root
        network_mode: "host"
        depends_on:
            - hbbr
        restart: unless-stopped
    hbbr:
        container_name: hbbr
        # ports:
        #   - 21117:21117
        #   - 21119:21119
        image: rustdesk/rustdesk-server:latest
        command: hbbr
        volumes:
            - ./data:/root
        network_mode: "host"
        restart: unless-stopped
    duplicati:
        image: lscr.io/linuxserver/duplicati:latest
        container_name: duplicati
        environment:
            - PUID=99 # nobody
            - PGID=100 # users
            - TZ=Etc/UTC
            - CLI_ARGS= #optional
        volumes:
            - ../../assets/server_management/duplicati/config:/config
            - /home/hong/Media/WesternDigital/Backup:/backups
            - /home/hong/Media/SeagateExpansion:/source
        ports:
            - 8200:8200
        restart: unless-stopped
    samba:
        image: dperson/samba
        env_file:
            - server_management.env
        environment:
            - TZ='Asia/Ho_Chi_Minh'
            - SHARE=WesternDigital;/mnt;yes;no;no;hong;none;none;WesternDigital
            - SHARE=SeagateExpansion;/mnt2;yes;no;no;hong;none;none;SeagateExpansion
            - SHARE=HomeServer;/mnt3;yes;no;no;hong;none;none;HomeServer
            - WORKGROUP=workgroup
            - USER=SERVER_USERNAME;SERVER_PASSWORD
            - NMBD=True
        networks:
            - default
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        read_only: false
        tmpfs:
            - /tmp
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - /home/hong/Media/WesternDigital:/mnt:z
            - /home/hong/Media/SeagateExpansion:/mnt2:x
    guacamole:
      image: jwetzell/guacamole
      container_name: guacamole
      restart: unless-stopped
      volumes:
        - ../../aseets/server_management/guacamole/postgres:/config
      ports:
        - 8190:8080
volumes:
  postgres:
    driver: local

networks:
  default:
