version: "3.7"
services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - WEBUI_PORT=8082
        volumes:
            - ../../../assets/qbit/config:/config
            - /media/hong/SeagateExpansion/Torrents:/downloads
        ports:
            - 8082:8082
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ../../../assets/bazarr/config:/config
            - /media/hong/WesternDigital/Torrents/Movies:/movies
            - /media/hong/WesternDigital/Torrents/TV_Shows:/tv
            - /media/hong/SeagateExpansion/Torrents/Movies:/movies
            - /media/hong/SeagateExpansion/Torrents/TV_Shows:/tv
        ports:
            - 6767:6767
        restart: unless-stopped
    # Manage your qBittorrent instance and Arr instances
    # qbitrr:
    #   image: feramance/qbitrr:latest
    #   user: 1000:1000 # Required to ensure the container is run as the user who has perms to see the 2 mount points and the ability to write to the CompletedDownloadFolder mount
    #   tty: true # Ensure the output of docker-compose logs qBitrr are properly colored.
    #   restart: unless-stopped
    #   # networks: This container MUST share a network with your Sonarr/Radarr instances
    #   environment:
    #     - TZ=Europe/London
    #   volumes:
    #     - /etc/localtime:/etc/localtime:ro
    #     - /path/to/appdata/qbitrr:/config  # Config folder for qBitrr
    #     - /path/to/completed/downloads/folder:/completed_downloads:rw # The script will ALWAYS require write permission in this folder if mounted, this folder is used to monitor completed downloads and if not present will cause the script to ignore downloaded file monitoring.
    #     # Now just to make sure it is clean, when using this script in a docker you will need to ensure you config.toml values reflect the mounted folders.
    #     # The same would apply to Settings.CompletedDownloadFolder
    #     # e.g CompletedDownloadFolder = /completed_downloads/folder/in/container

    #   logging: # this script will generate a LOT of logs - so it is up to you to decide how much of it you want to store
    #     driver: "json-file"
    #     options:
    #       max-size: "50m"
    #       max-file: 3
    #   depends_on: # Not needed but this ensures qBitrr only starts if the dependencies are up and running
    #     - qbittorrent
    #     - radarr-1080p
    #     - radarr-4k
    #     - sonarr-1080p
    #     - sonarr-anime
    #     - overseerr
    #     - ombi
